### ISSUE TITLE
[feat/fe/th-0009] 키워드 및 태그를 통한 테마 검색 기능 구현

### ISSUE THREAD

**Issue by lineJeong** [TeamWAGMI/LetsSeoul#142]
- 기능 설명 : 테마 검색 페이지에서 전체 테마 카드를 키워드 및 태그를 통해 검색하는 기능을 구현한다.

-`태그 검색` : 태그 누를 때마다 요청 발생, 다중 태그 선택 가능 
-`키워드 검색` : 버튼 or 엔터키 누를 때 요청 발생

- method : `get`

- location: `Search 컴포넌트 ("/search")`

- 기타(optional) :

**Comment by lineJeong** [comment]
- 로컬에서 get 요청 시 스텁 에러(status: 400) 발생 / 실제 API에서는 요청 method 수정 될 수 있음
상기의 이유로 API 작업 완료 후에 작업 진행할 예정 ( 마일스톤 Week 2 => Week 3으로 수정 )

**Comment by aka-nick** [comment]
해당 API의 http method는 `POST`로 변경되었습니다(`POST /api/v1/themes/search`) 😃
[이 문서](https://www.notion.so/0f28638e4d14448c9bfa157b8d32bf44)를 참고해주세요~
