### ISSUE TITLE
[feat/be/LO-0002] 특정유저 찜 장소 조회 api

### ISSUE THREAD

**Issue by JuSeong1130** [TeamWAGMI/LetsSeoul#151]
설명: 
- 기능 요약: 특정 유저가 리뷰를 남긴 장소들을 조회하는 api
- method: `GET`
- endpoint: `/api/v1/location/{userId}/wish`
- request(optional):
- response(optional):

**Comment by aka-nick** [comment]
`GET /api/v1/locations/wishes`로 변경

**Comment by aka-nick** [comment]
`GET /api/v1/locations/{userId}/wishes`로 다시 변경 😥
