### ISSUE TITLE
[feat/be/LO-0001] 특정유저 리뷰 장소 조회 api

### ISSUE THREAD

**Issue by JuSeong1130** [TeamWAGMI/LetsSeoul#152]
설명: 
- 기능 요약: 특정 유저가 리뷰를 남긴 장소들을 조회하는 api
- method: `GET`
- endpoint: `/api/v1/location/{userId}/review`
- request(optional):
- response(optional):

**Comment by aka-nick** [comment]
`GET /api/v1/locations/reviews`로 변경

**Comment by aka-nick** [comment]
`GET /api/v1/locations/{userId}/reviews로 다시 변경 😥
