### ISSUE TITLE
[feat/fe/au-001] 카카오 로그인 및 관련 정보 유지, 리다이렉트 구현

### ISSUE THREAD

**Issue by mellomello-made** [TeamWAGMI/LetsSeoul#25]
- 기능 설명 : 카카오 로그인 요청부터 로그인 유지, 로그인 정보 유지, 페이지 리다이렉트 등을 구현한다.
1. `카카오로 계속하기` 버튼 클릭 시, 로그인 페이지로 넘어간다. 
2. 카카오 로그인 성공했을 때 서버에서 리다이렉트 하는 페이지에서 암호화된 url 쿼리스트링으로 넘어오는 유저의 정보를 복호화 한다.
3. (전역관리) 복호화한 유저 정보는 양식에 맞춰 가공해 저장하고, 로그인 상태를 true 값으로 갱신한다.
4. 로그인을 시도한 직전 페이지로 이동한다.

- method : `없음`

- location: `Header 컴포넌트, loginData 컴포넌트`

- 기타(optional) : 
-redux toolkit 및 redux-persist 활용
-이후 확인해야할 사항
1. 서버에서 카카오 토큰이 만료 됐을 때 프론트에서 어떻게 처리해야 할지 체크 필요
2. 카카오 로그인 시 프론트 단에서 예외처리 해야 할 요소가 있는지 체크 필요

**Comment by lineJeong** [comment]
22/9/30 이슈 본문 수정 ( 작업 내용 구체화 및 변경 사항 반영 )
